version: '3'
services:

  database:
    image: "mysql:latest"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=fevermap
      - MYSQL_USER=fevermap
      - MYSQL_PASSWORD=feverpass
    volumes:
      - "database:/var/lib/mysql:rw"
